# Generated by Django 4.2.30 on 2026-06-05 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('register', 'User Registration'), ('login', 'User Login'), ('logout', 'User Logout'), ('verify', 'Land Verification'), ('create_record', 'Land Record Created'), ('update_record', 'Land Record Updated'), ('transfer_request', 'Transfer Request Submitted'), ('transfer', 'Ownership Transfer'), ('tamper_detect', 'Tamper Detection'), ('qr_generate', 'QR Code Generated'), ('admin_action', 'Admin Action')], db_index=True, max_length=25)),
                ('land_title', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('result', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('flagged', 'Flagged')], db_index=True, max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
