# Generated by Django 4.2.30 on 2026-06-05 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TamperLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('land_title', models.CharField(db_index=True, max_length=50)),
                ('tampered_block_index', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('detected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tamper_detections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tamper_logs',
                'ordering': ['-detected_at'],
            },
        ),
    ]
