# Generated by Django 4.2.30 on 2026-06-05 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LandRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title_number', models.CharField(db_index=True, help_text='Official land title number issued by the land registry', max_length=50, unique=True)),
                ('location', models.TextField(help_text='Physical address or plot description')),
                ('region', models.CharField(max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('area_sqm', models.DecimalField(decimal_places=2, help_text='Area in square metres', max_digits=14)),
                ('status', models.CharField(choices=[('verified', 'Verified'), ('disputed', 'Disputed'), ('transferred', 'Transferred'), ('pending', 'Pending Review'), ('flagged', 'Flagged – Possible Fraud')], db_index=True, default='pending', max_length=15)),
                ('registered_at', models.DateField(help_text='Date of official registration at the land registry')),
                ('qr_code_path', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_land_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Land Record',
                'verbose_name_plural': 'Land Records',
                'db_table': 'land_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('new_owner_name', models.CharField(max_length=255)),
                ('new_owner_national_id', models.CharField(max_length=30)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_requests', to='lands.landrecord')),
                ('new_owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transfers', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_requests_made', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_requests_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transfer_requests',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='OwnershipRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_name', models.CharField(help_text='Full legal name of owner', max_length=255)),
                ('owner_national_id', models.CharField(help_text='National ID of owner', max_length=30)),
                ('acquired_at', models.DateField(default=django.utils.timezone.now, help_text='Date ownership was acquired')),
                ('transferred_at', models.DateField(blank=True, help_text='Date ownership was transferred away', null=True)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('transfer_reason', models.TextField(blank=True, help_text='Reason for ownership transfer')),
                ('block_hash', models.CharField(help_text='SHA-256 hash of this ownership block', max_length=64)),
                ('prev_hash', models.CharField(blank=True, help_text='Hash of previous ownership block (null = genesis)', max_length=64, null=True)),
                ('block_index', models.PositiveIntegerField(default=0, help_text='Position in the chain')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ownership_records', to='lands.landrecord')),
                ('owner', models.ForeignKey(blank=True, help_text='System user who owns this land (if registered)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_lands', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ownership Record',
                'verbose_name_plural': 'Ownership Records',
                'db_table': 'ownership_records',
                'ordering': ['land', 'block_index'],
            },
        ),
        migrations.AddConstraint(
            model_name='ownershiprecord',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('land',), name='unique_current_owner_per_land'),
        ),
    ]
