# Generated by Django 4.2.30 on 2026-10-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landrecord',
            name='area_acres',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='landrecord',
            name='beacon_numbers',
            field=models.CharField(blank=True, help_text='Comma-separated beacon references', max_length=255),
        ),
        migrations.AddField(
            model_name='landrecord',
            name='deed_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='landrecord',
            name='deed_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='landrecord',
            name='encumbrances',
            field=models.TextField(blank=True, default='None'),
        ),
        migrations.AddField(
            model_name='landrecord',
            name='gps_coordinates',
            field=models.CharField(blank=True, help_text='e.g. 5.6500° N, 0.1500° W', max_length=100),
        ),
        migrations.AddField(
            model_name='landrecord',
            name='land_type',
            field=models.CharField(blank=True, choices=[('freehold', 'Freehold'), ('leasehold_50', 'Leasehold (50 years)'), ('leasehold_99', 'Leasehold (99 years)'), ('stool_land', 'Stool Land'), ('state_land', 'State Land')], max_length=20),
        ),
        migrations.AddField(
            model_name='landrecord',
            name='land_use',
            field=models.CharField(blank=True, choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('agricultural', 'Agricultural'), ('mixed', 'Mixed Use')], max_length=20),
        ),
        migrations.AddField(
            model_name='landrecord',
            name='locality',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='landrecord',
            name='plot_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='landrecord',
            name='stamp_duty_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='landrecord',
            name='stamp_duty_ref',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='landrecord',
            name='survey_plan_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='landrecord',
            name='surveyor_license',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='landrecord',
            name='surveyor_name',
            field=models.CharField(blank=True, help_text='Licensed surveyor or firm name', max_length=150),
        ),
        migrations.AddField(
            model_name='landrecord',
            name='town_planning_approval',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
