# Generated by Django 4.2.30 on 2026-10-05 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lands', '0002_landrecord_area_acres_landrecord_beacon_numbers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landrecord',
            name='status_change_reason',
            field=models.TextField(blank=True, default='', help_text='Reason given for the most recent status change (e.g. why a land was marked Disputed)'),
        ),
        migrations.AddField(
            model_name='landrecord',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landrecord',
            name='status_changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='land_status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='previous_owner_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='previous_owner_national_id',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
