# Generated by Django 4.2.30 on 2026-10-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0003_landrecord_status_change_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownershiprecord',
            name='owner_contact',
            field=models.CharField(blank=True, help_text="Owner's phone number or contact", max_length=30),
        ),
    ]
